=== gahyeon-park/2019/xml/practice/attributeDTDPractice.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT memberList (member*, bestMember, newMember)>
	<!ELEMENT member (name, phone, address)>
	<!ATTLIST member grade CDATA "associated">
		<!ELEMENT name (#PCDATA)>
		<!ATTLIST memberNum ID #REQUIRED
			  idNum NMTOKENS #REQUIRED>
		<!ELEMENT phone (#PCDATA)>
		<!ELEMENT address (#PCDATA)>
		<!ATTLIST address location (jeon|gyeong|gang|gyang|seo) #IMPLIED>
	<!ELEMENT bestMember EMPTY>
	<!ATTLIST bestMember memberNum IDREF #REQUIRED>
	<!ELEMENT newMember EMPTY>
	<!ATTLIST newMember memberNum IDREFS #REQUIRED>

=== gahyeon-park/2019/xml/practice/attributeDTDPractice.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE memberList SYSTEM "./attributeDTDPractice.dtd">

<memberList>
	<member grade="regular">
		<name memberNum="regular0001" idNum="971108">홍길동</name>
		<phone>011-234-5678</phone>
		<address location="seo">서울시</address>
	</member>
	<member>
		<name memberNum="associated0001" idNum="951109">강감찬</name>
		<phone>062-230-6624</phone>
		<address location="gyeong">부산시</address>
	</member>
	<member grade="admin">
		<name memberNum="admin0001" idNum="123456">이순신</name>
		<phone>062-230-7963</phone>
		<address>광주시</address>
	</member>
	<bestMember memberNum="admin0001"/>
	<newMember memberNum="regular0001 associated0001"/>
</memberList>
