=== gahyeon-park/2019/xml/practice/DTDoutPractice.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT monthBestSeller (bestSeller)+>
	<!ELEMENT bestSeller (type, kind?, title, author+, company*, date, discription)>
		<!ELEMENT type (economy|computer|fiction|nonfiction)*>
			<!ELEMENT economy EMPTY>
			<!ELEMENT computer EMPTY>
			<!ELEMENT fiction EMPTY>
			<!ELEMENT nonfiction EMPTY>
		<!ELEMENT kind (#PCDATA)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT author (#PCDATA)>
		<!ELEMENT company (#PCDATA)>
		<!ELEMENT date EMPTY>
			<!ATTLIST date
				year CDATA #REQUIRED
				month CDATA #REQUIRED
				day CDATA #REQUIRED>
		<!ELEMENT discription ANY>

=== gahyeon-park/2019/xml/practice/DTDoutPractice.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE monthBestSeller SYSTEM "DTDoutPractice.dtd">

<monthBestSeller>
	<bestSeller>
		<type><economy/><nonfiction/></type>
		<kind>금융, 증권</kind>
		<title>부자 아빠, 가난한 아빠</title>
		<author>로버트 기요사키</author>
		<author>Rovert Kiyosaki</author>
		<company>황금가지</company>
		<date year="2002" month="3" day="10"/>
		<discription>
			<author>홍길동</author>
			<author>이순신</author>
			<company>은뿌리</company>
		</discription>
	</bestSeller>
</monthBestSeller>
